PROGS               =	forward_list64 forward_list \
	bench_aligned_alloc bench_malloc forward_list64_test \
	bench_cacheline bench_posix_memalign

SRCS.forward_list64      =	forward_list64.cc
SRCS.forward_list        =	forward_list.cc
SRCS.bench_posix_memalign=	bench_posix_memalign.c
SRCS.bench_aligned_alloc =	bench_aligned_alloc.c
SRCS.bench_malloc        =	bench_malloc.c
SRCS.bench_cacheline     =	bench_cacheline.c
SRCS.forward_list64_test =	forward_list64_test.cc

WARNS  =	4
CXXSTD =	c++17

CXXOPTS ?=	-O3 -g

#LDFLAGS += -L/opt/pkg/lib -R/opt/pkg/lib -ljemalloc

.include <mkc.mk>

 # Created by Aleksey Cheusov <vle@gmx.net>
 #
 # Permission is hereby granted, free of charge, to any person or organization obtaining
 # a copy of the software and accompanying documentation covered by this license
 # (the “Software”) to use, reproduce, display, distribute, execute, and transmit
 # the Software, and to prepare derivative works of the Software, and to permit
 # third-parties to whom the Software is furnished to do so, all subject to the following:
 #
 # The copyright notices in the Software and this entire statement, including
 # the above license grant, this restriction and the following disclaimer, must be
 # included in all copies of the Software, in whole or in part, and all derivative
 # works of the Software, unless such copies or derivative works are solely in
 # the form of machine-executable object code generated by a source language processor.
 #
 # THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 # INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 # A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT
 # HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER
 # LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
 # IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
